name: List Directories and Their Latest Git Commit Date (Ubuntu)

on:
  schedule:
    - cron: '2 2 * * 0'  # Runs weekly, every Sunday at 01:01 UTC (1 hour after the first workflow)
  workflow_dispatch:  # Allows manual execution

jobs:
  list_directories:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}
          fetch-depth: 0  # Ensure full history is fetched

      - name: List Directories and Latest Commit Date
        run: |
          echo "Generating report of directories and their latest commit dates..."
          if [ -d "./conteudo" ]; then
            # Create or overwrite the report file
            echo "Name, Last Commit Message, Last Commit Date" > directory_modifications.txt

            # List all directories in the 'conteudo' folder
            for dir in $(find ./conteudo -mindepth 1 -maxdepth 1 -type d); do
              # Get the directory name
              dir_name=$(basename "$dir")

              # Debug information
              echo "Processing directory: $dir_name"

              # Get the last commit for the directory using git log
              last_commit_message=$(git log -1 --pretty=format:"%s" -- "$dir")
              last_commit_date=$(git log -1 --pretty=format:"%cd" --date=format:"%Y-%m-%d %H:%M:%S" -- "$dir")
              
              # Debug output to verify the correct directory and git log output
              echo "Directory: $dir_name"
              echo "Last Commit Message: $last_commit_message"
              echo "Last Commit Date: $last_commit_date"
              
              # Append the information to the report file
              echo "$dir_name, $last_commit_message, $last_commit_date" >> directory_modifications.txt
            done

            echo "Report generated: directory_modifications.txt"
          else
            echo "Directory './conteudo' does not exist."
          fi
          
      - name: Commit and Push Changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add directory_modifications.txt
          git commit -m "Updated directory modification times report" || echo "No changes to commit"
          git push origin HEAD:${{ github.ref }}
